models/Comment.php
<?php


namespace app\models;

use DateTime;
use yii\db\ActiveRecord;

/**
 * @property int $id
 * @property string $comment
 * @property float $author
 * @property string $date
 * @property int $reply_id
 * @property int $author_id
 */
class Comment extends ActiveRecord
{
    /**
     * @var mixed|null
     */


    public static function tableName()
    {
        return '{{comments}}';
    }

    public function attributeLabels()
    {
        return [
            'comment' => 'Ваш комментарий',

        ];
    }

    public function rules()
    {
        return [
            ['comment', 'required','message'=>'Введите текст комментария.'],
            [['comment'],'string', 'max' => 100,'tooLong'=>'Комментарий превышает 100 символов.'],
            //['reply', 'required','message'=>'Введите текст ответа на комментарий.'],

        ];
    }

    static function getDateDiff($date){

        $now = new DateTime();
        //$new = $now->modify('-1 day');
        return date_diff($now,date_create($date,timezone_open("Europe/Moscow")));

    }

    static function getArrTime($interval)
    {
        if($interval->y > 0) {
            return ['год', 'года', 'лет'];
        }
        if($interval->m > 0){
            return ['месяц','месяца','месяцев'];
        }
        if($interval->d > 0){
            return ['день','дня','дней'];
        }
        if($interval->h > 0){
            return ['час','часа','часов'];
        }
        if($interval->i > 0){
            return ['минута','минуты','минут'];
        }
        if($interval->s > 0){
            return ['секунда','секунды','секунд'];
        }


    }
}

controllers/CommentController.php
<?php

namespace app\controllers;

use app\models\Comment;
use app\repositories\CommentRepository;
use app\helpers\DeclensionHelper;
use app\services\CommentService;
use app\services\EmailNotifyService;
use DateTime;
use DomainException;
use Yii;
use yii\db\Exception;
use yii\db\Query;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotAcceptableHttpException;
use yii\web\NotFoundHttpException;


class CommentController extends Controller
{
    public function actionAjax($data)
    {
        if (!Yii::$app->request->isAjax) {
            throw new NotAcceptableHttpException("Что-то пошло не так...");
        }

        $comments = Comment::find()
            ->where(['and', ['reply_id' => null], ['<', 'id', $data]])
            ->orderBy(['id' => SORT_DESC])
            ->limit(3)
            ->all();

        $replies = Comment::find()
            ->where(['not', ['reply_id' => null]])
            ->all();

        $htmlReplies = '';
        foreach ($comments as $comment) {

            $commentReplies = [];
            foreach ($replies as $rep) {
                if ($comment->id == $rep->reply_id) {
                    $commentReplies[] = $rep;
                }
            }
            $htmlReplies .= $this->renderPartial('_comment', ['comment' => $comment, 'replies' => $commentReplies]);
        }

        $isLast = false;

        $count = Comment::find()
            ->where(['and', ['reply_id' => null], ['<', 'id', $data]])
            ->count();

        if ($count <= 3) {
            $isLast = true;
        }

        return json_encode([
            'html' => $htmlReplies,
            'isLast' => $isLast
        ]);
    }

    public function actionIndex()
    {
        //$commentsRepository = new CommentRepository();
        $commentsRepository = Yii::$container->get(CommentRepository::class);

        $comments = $commentsRepository->getCommentsWithReplies();

        return $this->render('index', ['comments' => $comments]);

    }

    public function actionCreate()
    {
        if (Yii::$app->user->isGuest) {
            throw new ForbiddenHttpException('Необходимо авторизоваться!');
        }
        $comment = new Comment();

        if ($comment->load(Yii::$app->request->post()) && $comment->validate()) {

            $commentService = Yii::$container->get(CommentService::class);

            try {
                $commentService->create($comment, Yii::$app->user->id);
            } catch (DomainException $e) {

                Yii::$app->session->setFlash('danger', $e->getMessage());
                return $this->redirect('index');

            }

            Yii::$app->session->setFlash('success', "Ваш комментарий успешно добавлен!");
            //exit('Ваш комментарий добавлен!');
            return $this->redirect('index');
        }

      /*  $emailNotifyService = Yii::$container->get(EmailNotifyService::class);

        $emailNotifyService->send();*/

        return $this->render('create', ['model' => $comment]);

    }

    public function actionDelete($id)
    {
        $comment = Comment::findOne($id);

        if (!$comment) {
            Yii::$app->session->setFlash('danger', "Выбранной записи в таблице не существует!");
            return $this->redirect('index');
        }

        /*if (Yii::$app->user->id != $comment->author) {

            Yii::$app->session->setFlash('danger', "Ошибка доступа");
            return $this->redirect('index');
        }*/

        //$comment->delete();

        $commentService = Yii::$container->get(CommentService::class);

        try {
            $commentService->delete($comment, Yii::$app->user->id);
        } catch (DomainException $e) {

            Yii::$app->session->setFlash('danger', $e->getMessage());
            return $this->redirect('index');

        }

        Yii::$app->session->setFlash('success', "Комментарий удален!");
        return $this->redirect('index');

    }

    public function actionUpdate($id)
    {
        if (Yii::$app->user->isGuest) {
            throw new ForbiddenHttpException('Необходимо авторизоваться!');
        }

        $comment = Comment::findOne($id);
        if (!$comment) {
            throw new NotFoundHttpException();
        }
        //существует ли такой пользователь?
        //добавить,что автор-тек.пользователь.
        //"Коммент не найден и у вас нет прав".
        //Добавит flesh-сообщение,что коммент добавлен.

        //if (Yii::$app->user->id != $comment->author) {
        /*if (Yii::$app->user->identity->username != $comment->author) {
            Yii::$app->session->setFlash('danger', "Ошибка доступа");
            return $this->redirect('index');
        }*/

        if ($comment->load(Yii::$app->request->post()) && $comment->validate()) {

            $commentService = Yii::$container->get(CommentService::class);

            try {
                $commentService->update($comment, Yii::$app->user->id);
            } catch (DomainException $e) {

                Yii::$app->session->setFlash('danger', $e->getMessage());
                return $this->redirect('index');

            }

            /*$comment->date = date('Y-m-d H:i:s');
            $comment->save();*/

            Yii::$app->session->setFlash('success', "Комментарий успешно обновлен!");
            return $this->redirect('index');
        }

        return $this->render('update', ['model' => $comment]);
    }

    public function actionReply($id)
    {
        if (Yii::$app->user->isGuest) {
            throw new ForbiddenHttpException('Необходимо авторизоваться!');
        }

        $comment = Comment::findOne($id);
        if (!$comment) {
            throw new NotFoundHttpException();
        }

        $reply = new Comment();

        if ($reply->load(Yii::$app->request->post()) && $reply->validate()) {

            $reply->reply_id = $id;
            $reply->author = Yii::$app->user->identity->username;
            $reply->date = date('Y-m-d H:i:s');
            $reply->save();

            Yii::$app->session->setFlash('success', "Вы ответили на комментарий!");
            //exit('Ваш комментарий добавлен!');
            return $this->redirect('index');
        }

        return $this->render('reply', ['comment' => $comment, 'reply' => $reply]);


    }


}

views/comment/_comment.php
<?php

use app\helpers\DeclensionHelper;
use app\models\Comment;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use app\repositories\CommentRepository;

/**
 * @var \yii\web\View $this
 * @var Comment $comment
 * @var Comment[] $replies
 */
?>

<!--<div class="comment" data-id="<?//$comment['id'] ?>">
    <div style="background-color: rgba(196,252,214,0.65);">
        <b><?// $comment['author'] ?></b>&nbsp<?// $comment['date'] ?></div>
    <div><?// $comment['comment'] ?></div>
    <br>
</div>-->

<div class="comment" data-id="<?= $comment->id ?>">

    <div style="background-color: rgba(196,252,214,0.65);">
        <b><?= $comment->author ?></b>&nbsp<?= $comment->date ?></div>

    <?php if ((!Yii::$app->user->isGuest) && (Yii::$app->user->identity->username) === $comment->author) : ?>

        <div class="icon">
            <div class="deleteIcon" onclick="deleteFunction(<?= $comment->id ?>)"
                 style=" float: right;">

                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#3374FF"
                     class="bi bi-trash-fill"
                     viewBox="0 0 16 16">
                    <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                </svg>
            </div>

            <div>
                <a href="<?= Yii::$app->urlManager->createUrl(['/comment/update', 'id' => $comment->id]) ?>"
                   style="float: right;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-pencil-fill" viewBox="0 0 16 16">
                        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                    </svg>
                </a>
            </div>
        </div>

    <?php endif; ?>

    <div><?= $comment->comment ?></div>

    <div style="color:#d3d3d3 ">
        <?php $dateDiff = Comment::getDateDiff($comment->date); ?>
        <?= DeclensionHelper::declension(($dateDiff), Comment::getArrTime($dateDiff)) ?>
    </div>
    <br>

    <div class="reply" style="position: absolute;left: 500px;">
        <a href="<?= Yii::$app->urlManager->createUrl(['/comment/reply', 'id' => $comment->id]) ?>">Ответить</a>
    </div><br><br>

    <?php foreach ($replies as $reply): ?>

        <div class="reply">

            <div style="background-color: rgba(183,224,225,0.65);margin-left: 5%">
                <b><?= $reply->author ?></b>&nbsp<?= $reply->date ?></div>

            <div style="margin-left: 5%"><?= $reply->comment ?></div>

            <div style="margin-left: 5%; color:#d3d3d3 ">
                <?php $dateDiffReplies = Comment::getDateDiff($reply->date) ?>
                <?= DeclensionHelper::declension($dateDiffReplies, Comment::getArrTime($dateDiffReplies)) ?>
            </div>
            <br>

        </div>

    <?php endforeach; ?>

</div>

<?php
//var_dump($arr);

views/comment/create.php
<?php

/* @var $model app\models\Comment */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;


?>

<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'comment')->textarea(['rows' => 6]) ?>

<div class="form-group">

    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>

</div>

<?php ActiveForm::end(); ?>

views/comment/index.php
<?php

use app\helpers\DeclensionHelper;
use app\models\Comment;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use app\repositories\CommentRepository;
use app\assets\AppAsset;

/**
 * @var \yii\web\View $this
 * @var array $comments
 */

$this->registerCssFile('/css/comment.css');


?>

    <p><b>Комментарии:</b></p><br>

    <div id="comment-list">

        <?php foreach ($comments as $commentArray): ?>

            <?php /** @var Comment $comment */ ?>

            <?php $comment = $commentArray['comment']; ?>

            <div class="comment" data-id="<?= $comment->id ?>">
                <div style="background-color: rgba(196,252,214,0.65);">
                    <b><?= $comment->author ?></b>&nbsp<?= $comment->date ?></div>


                <?php if ((!Yii::$app->user->isGuest) && (Yii::$app->user->identity->username) === $comment->author) : ?>

                <div class="icon">
                    <div class="deleteIcon" onclick="deleteFunction(<?= $comment->id ?>)"
                         style=" float: right;">

                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#3374FF"
                             class="bi bi-trash-fill"
                             viewBox="0 0 16 16">
                            <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                        </svg>
                    </div>

                    <div>
                        <a href="<?= Yii::$app->urlManager->createUrl(['/comment/update', 'id' => $comment->id]) ?>"
                           style="float: right;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                            </svg>
                        </a>
                    </div>
                </div>

                <?php endif; ?>

                <div><?= $comment->comment ?></div>

                <div style="color:#d3d3d3 ">
                    <?php $dateDiff = Comment::getDateDiff($comment->date); ?>
                    <?= DeclensionHelper::declension(($dateDiff), Comment::getArrTime($dateDiff)) ?>
                </div>

                <div class="reply" style="position: absolute;left: 500px;">
                    <a href="<?= Yii::$app->urlManager->createUrl(['/comment/reply', 'id' => $comment->id]) ?>">Ответить</a>
                </div><br><br>


                <div class="replies">

                    <?php foreach ($commentArray['replies'] as $reply): ?>

                        <div class="repLy">

                            <div style="background-color: rgba(183,224,225,0.65);margin-left: 5%">
                                <b><?= $reply->author ?></b>&nbsp<?= $reply->date ?></div>

                            <div style="margin-left: 5%"><?= $reply->comment ?></div>

                            <div style="margin-left: 5%; color:#d3d3d3 ">
                                <?php $dateDiffReplies = Comment::getDateDiff($reply->date); ?>
                                <?= DeclensionHelper::declension(($dateDiffReplies), Comment::getArrTime($dateDiffReplies)) ?>
                            </div>
                            <br>

                        </div>

                    <?php endforeach; ?>

                </div>

            </div>

        <?php endforeach; ?>

    </div>


<?php if (!Yii::$app->user->isGuest): ?>

    <div class="addIcon">
        <a href="<?= Yii::$app->urlManager->createUrl(['/comment/create']) ?>">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill=#3374FF
                 class="bi bi-chat-left-dots-fill" viewBox="0 0 16 16">
                <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm5 4a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm4 0a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
            </svg>
        </a>
    </div><br>

<?php endif; ?>

    <!--<script>
        function deleteFunction(id) {

            if (confirm("Вы уверены,что хотите удалить комментарий?") === true) {
                document.location.href = "delete?id=" + id;
            } else {
                document.location.href = "index";
            }
        }
    </script>-->

        <!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {

                $("#but1").click(function () {
                    let lastCommentId = $('#comment-list .comment:last-child').data("id");
                    $.ajax({
                        url: '/comment/ajax',
                        data: {data: lastCommentId},
                        dataType: 'json',
                        success: function (json) {
                            $("#comment-list").append(json.html);

                            if (json.isLast) {
                                $("#but1").hide();
                            }
                        }
                    });

                });

            });
        </script>-->

       <input class="button1" id="but1" type="button" value="Показать еще комментарии"/>

    <style>

    </style>

<?php
//var_dump(DateTime::createFromFormat("Y:m:d H:i:s",$comment['comment']['date']));
//var_dump(date_diff(new DateTime(),date_create('2022-03-23 09:44:01',timezone_open("Europe/Moscow"))));
//var_dump($comment);
//var_dump($reply);

views/comment/reply.php
<?php

/**
* @var $comment app\models\Comment
 * @var $reply app\models\Comment
*/

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

?>

<p>Комментарий:</p>
<style>
    .comment{
        border: solid 1px lightgray;
    }
</style>
<div class="comment"><?= $comment->comment ?></div><br>

<?php $form = ActiveForm::begin(); ?>

<?= $form->field($reply, 'comment')->textarea(['rows' => 6])->label('Ответ:')?>


<div class="form-group">

    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>

</div>

<?php ActiveForm::end(); ?>

views/comment/test.php
<?php

use app\helpers\DeclensionHelper;
use app\models\Comment;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use app\repositories\CommentRepository;

/**
 * @var \yii\web\View $this
 * @var Comment[] $comments
 */

$this->registerCssFile('/css/comment.css');
?>


<?php foreach($comments as $comment): ?>

    <p xmlns="http://www.w3.org/1999/html"> <b>Комментарий:</b> </p><br>



    <div style="background-color: rgba(196,252,214,0.65);"><b><?= $comment['comment']['author'] ?></b>&nbsp<?= $comment['comment']['date'] ?></div>



    <?php if ((!Yii::$app->user->isGuest) && (Yii::$app->user->identity->username) === $comment['comment']['author']) : ?>

        <div class="deleteIcon" onclick="myFunction(<?= $comment['comment']['id'] ?>)" style=" float: right;">

            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#3374FF" class="bi bi-trash-fill"
                 viewBox="0 0 16 16">
                <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
            </svg>
        </div>

        <div>
            <a href="<?= Yii::$app->urlManager->createUrl(['/comment/update', 'id' => $comment['comment']['id']]) ?>"
               style="float: right;">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-pencil-fill" viewBox="0 0 16 16">
                    <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                </svg>
            </a>
        </div>

    <?php endif;?>

    <div><?= $comment['comment']['comment'] ?></div>

    <div><font color="#d3d3d3"> <?= DeclensionHelper::declension(Comment::getDateDiff($comment['comment']['date']),
                (Comment::getArrTime(Comment::getDateDiff($comment['comment']['date'])))) ?></font></div>

    <div class="reply">  <a href="reply?id=<?= $comment['comment']['id'] ?>">Ответить</a> </div> <br><br>

    <div style="margin-left: 5%" ><p> <b>Ответы:</b> </p> </div>


    <?php for ($i = 0; $i < count($comment['replies']);$i++) :?>

        <div style="background-color: rgba(183,224,225,0.65);margin-left: 5%"><b><?= $comment['replies'][$i]['author'] ?></b>&nbsp<?= $comment['replies'][$i]['date'] ?></div>

        <div style="margin-left: 5%"><?= $comment['replies'][$i]['comment'] ?></div>

        <div style="margin-left: 5%"><font color="#d3d3d3"> <?= DeclensionHelper::declension(Comment::getDateDiff($comment['replies'][$i]['date']),
                    (Comment::getArrTime(Comment::getDateDiff($comment['replies'][$i]['date'])))) ?></font></div><br>

    <?php endfor ?>

    <?php if(!next($comments)):?>

        <div hidden><?= $lastIndex = $comment['comment']['id']?></div>

    <?php endif;?>

<?php endforeach; ?>

<style>
    /*.addIcon{*/
    /*   float: left;*/
    /*   }*/

    .reply{
        position: absolute;
        left: 500px;
    }

    .show{
        position: absolute;
        right: 500px;
    }
</style>

<?php if(!Yii::$app->user->isGuest): ?>

    <div class="addIcon" >
        <a href="create">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill=#3374FF class="bi bi-chat-left-dots-fill" viewBox="0 0 16 16">
                <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm5 4a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm4 0a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
            </svg>
        </a>
    </div><br>

<?php endif;?>

<script>
    function myFunction(id) {

        if(confirm("Вы уверены,что хотите удалить комментарий?") === true){
            document.location.href = "delete?id="+id;
        }else {
            document.location.href = "index";
        }
    }
</script>

views/comment/update.php
<?php
/**
 * @var $model app\models\Comment
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;


$form = ActiveForm::begin(); ?>

<?= $form->field($model, 'comment')->textarea(['rows' => 6]) ?>

<div class="form-group">
            <div class="offset-lg-1 col-lg-11">
                <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>
            </div>
</div>
<?php ActiveForm::end(); ?>